### ISSUE TITLE
project.el Find File opens dired even with override dired mode

### ISSUE THREAD

**Issue by andcarnivorous** [alexluigit/dirvish#22]
Hi, awesome package. I am encountering an issue though with project.el.
Using:
Emacs 27.2
project.el 0.8.1
dirvish 20220325.1418 
When I open one of my projects with project.el and use *Find Directory* it ends up using dired instead of dirvish although I have specified in my config to override dired:

```lisp
(use-package dirvish
  :custom
  (dirvish-bookmarks-alist
   '(("h" "~/"                          "Home")
     ("d" "~/Downloads/"                "Downloads")
     ("m" "/mnt/"                       "Drives")))
  :config
  (dirvish-override-dired-mode)
  (dirvish-peek-mode)
  (setq dirvish-attributes '(all-the-icons file-size))
  :bind
  (:map dired-mode-map
        ("SPC" . dirvish-show-history)
        ("r"   . dirvish-roam)
        ("b"   . dirvish-goto-bookmark)
        ("f"   . dirvish-file-info-menu)
        ("M-a" . dirvish-mark-actions-menu)
        ("M-s" . dirvish-setup-menu)
        ("M-f" . dirvish-toggle-fullscreen)
        ([remap dired-summary] . dirvish-dispatch)
        ([remap dired-do-copy] . dirvish-yank)
        ([remap mode-line-other-buffer] . dirvish-other-buffer)))
```

Could this be because of something conflicting somewhere else in my config file or is this something kind of expected?

**Comment by alexluigit** [comment]
>Could this be because of something conflicting somewhere else in my config file or is this something kind of expected?

I'm not sure about it, I pushed a patch for it, you can check if it solves the issue for you. If it fails to do so, please give me a better description on this part: 

>When I open one of my projects with project.el and use Find Directory 

What command did you use to open the project? What did you mean by 'Find Directory', this is not a command AFAIK.

**Comment by andcarnivorous** [comment]
@alexluigit I updated the `darvish.el` file with your last commit but the issue still persists.
To be clearer on when this happens, after running `project-switch-project` I run `project-find-dir` and it opens dired instead of dirvish. I have overwritten the function in my config to circumvent this in the last line of the function:
```lisp
(defun project-find-dir ()
  "Start Dired in a directory inside the current project."
  (interactive)
  (let* ((project (project-current t))
         (all-files (project-files project))
         (completion-ignore-case read-file-name-completion-ignore-case)
         ;; FIXME: This misses directories without any files directly
         ;; inside.  Consider DIRS-ONLY as an argument for
         ;; `project-files-filtered', and see
         ;; https://stackoverflow.com/a/50685235/615245 for possible
         ;; implementation.
         (all-dirs (mapcar #'file-name-directory all-files))
         (dir (funcall project-read-file-name-function
                       "Dired"
                       ;; Some completion UIs show duplicates.
                       (delete-dups all-dirs)
                       nil nil)))
    (dirvish dir)))

```

**Comment by alexluigit** [comment]
Have you ever tested it with `emacs -q`?
```
emacs -q -L dirvish -l dirvish --eval "(progn (dirvish-override-dired-mode) 
                                         (project-switch-project \"fill/in/path/to/your/project\"))"
```

**Comment by andcarnivorous** [comment]
> Have you ever tested it with `emacs -q`?
> 
> ```
> emacs -q -L dirvish -l dirvish --eval "(progn (dirvish-override-dired-mode) 
>                                          (project-switch-project \"fill/in/path/to/your/project\"))"
> ```

It does work in that case (need to load project.el as well though), it means something then  in my config is messing up the override I guess

**Comment by alexluigit** [comment]
You probably need to check the advices attached to `dired` command. Evaluate `(describe-function 'dired)`, you should see something like 
```
This function has :around advice: ‘ls-lisp--dired’.
This function has :around advice: ‘dirvish-dired-ad’.
```
Everything other than this two might be the cause of the problem.

**Comment by andcarnivorous** [comment]
You are right, indeed those lines are visible only if I use `(dirvish-override-dired-mode)` outside of the use-package and at the end of my config (although the dirvish use-package is already at the end of it). The setup of my use-package dirvish is basically a copy-pasta from one of the ones in the `Configurations.org`. I'll try to dig a bit more into what may be causing this behavior specifically, but thanks for pointing me to the right way!

**Comment by alexluigit** [comment]
Ah, I see. I think add `:demand t` in your `use-package` block or move `(dirvish-override-dired-mode)` under `:init` keyword can solve this. I might need to mention this in the example config as well.
